[package]
name = "smart-thermo-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.19.2", features = [
    "net",
    "macros",
    "rt-multi-thread",
    "io-util",
    "sync",
    "time",
] }
